# Generated by Django 2.0.6 on 2018-07-20 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180720_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 20, 11, 31, 39, 568069, tzinfo=utc)),
        ),
    ]
